- website/guides/tutorial/how-to-deploy-nuxtjs.md
- website/guides/tutorial/how-to-deploy-nuxtjs.md.erb
Hi there !
I added the differents "How To" for the server hosting & static hosting in order to deploy on Qovery every type of Nuxt application 🥰
> docs(tutorials): rewrite nuxtjs tutorial

- website/docs/community/reward/bug-bounty.md
Fixed some typos found in the bug bounty documentation.
> Fixed typos

- website/docs/using-qovery/configuration/application.md
- website/docs/using-qovery/configuration/application.md.erb
Doc updated with advanced settings (description of deployment.delay_start_time_sec).
> advancedsettings_PRDT-932

- website/package-lock.json
- website/yarn.lock
Reverts Qovery/documentation#196
> Revert "chore(deps): bump minimist from 1.2.5 to 1.2.7 in /website"

- website/package-lock.json
- website/package.json
- website/yarn.lock
Reverts Qovery/documentation#97
> Revert "chore(deps): bump prismjs from 1.20.0 to 1.27.0 in /website"

- website/yarn.lock
Reverts Qovery/documentation#94
> Revert "chore(deps): bump ajv from 6.12.0 to 6.12.6 in /website"

- website/yarn.lock
Reverts Qovery/documentation#197
> Revert "chore(deps): bump ansi-regex from 5.0.0 to 5.0.1 in /website"

- website/package-lock.json
- website/yarn.lock
Reverts Qovery/documentation#198
> Revert "chore(deps): bump color-string from 1.5.3 to 1.9.1 in /website"

- website/package-lock.json
- website/yarn.lock
Reverts Qovery/documentation#200
> Revert "chore(deps): bump browserslist from 4.11.1 to 4.21.4 in /website"

- website/package-lock.json
- website/yarn.lock
Reverts Qovery/documentation#199
> Revert "chore(deps): bump json-schema and jsprim in /website"

- website/docusaurus.config.js
- website/package.json
- website/yarn.lock
- Add a plugin for zoom image behavior (like medium and Qovery blog)
> feat: add plugin zoom image

- website/docs/using-qovery/configuration/environment.md
- website/docs/using-qovery/configuration/environment.md.erb
auto-delete is now within the preview env section
> moved auto-deploy into preview env section

- website/docs/using-qovery/configuration/environment.md
- website/docs/using-qovery/configuration/environment.md.erb
- website/docs/using-qovery/integration/terraform.md
- website/docs/using-qovery/integration/terraform.md.erb
added terraform exporter references in environment and terraform sections
> feat: added terraform exporter

- website/docs/getting-started/install-qovery/gcp/cluster-managed-by-qovery/initialize-your-cloud-account-to-deploy-GKE.md
- website/docs/getting-started/install-qovery/gcp/cluster-managed-by-qovery/initialize-your-cloud-account-to-deploy-GKE.md.erb
> chore: GCP init account add services links

- website/docs/using-qovery/configuration/application.md
- website/docs/using-qovery/configuration/application.md.erb
PR to test the algolia integration
> test algolia

- website/docs/using-qovery/configuration/advanced-settings.md
- website/docs/using-qovery/configuration/advanced-settings.md.erb
> feat(ENG-1777): HPA allow to scale based on memory

- website/docs/using-qovery/configuration/cluster-advanced-settings.md
- website/docs/using-qovery/configuration/cluster-advanced-settings.md.erb
> feat(ENG-1779): nginx log-format in advanced settings

- website/docs/using-qovery/configuration/cluster-advanced-settings.md
- website/docs/using-qovery/configuration/cluster-advanced-settings.md.erb
> fix(ENG-1779): nginx log-format-escaping typo

- Dockerfile
This reverts commit 6c235c23b1b9e0afffe9aad5b9b4ebe6a42ed6e6.
> Revert "chore: Use our public container registry (#454)"

- website/src/theme/Layout/styles.css
- This fix allows to remove unnecessary scroll when we have `div` from intercom or navigator extension
> fix: remove unwanted bottom scroll

- website/docs/using-qovery/configuration/cluster-advanced-settings.md
- website/docs/using-qovery/configuration/cluster-advanced-settings.md.erb
> feat(ENG-1903): nginx support use_forwarded_headers & compute_full_forwarded_for

- website/guides/tutorial/deploy-jupyterhub-qovery.md
- website/guides/tutorial/deploy-jupyterhub-qovery.md.erb
Fix typo on tab name
Fix description and add link to DaemonSet with Karpenter
> fix tuto for JupyterHub

- website/docs/using-qovery/configuration/advanced-settings.md
- website/docs/using-qovery/configuration/advanced-settings.md.erb
- website/docs/using-qovery/configuration/cluster-advanced-settings.md
- website/docs/using-qovery/configuration/cluster-advanced-settings.md.erb
> chore(ENG-1927): add nginx snippets and rate limit options

- website/docs/using-qovery/configuration/cluster-advanced-settings.md
- website/docs/using-qovery/configuration/cluster-advanced-settings.md.erb
> chore(ENG-1927): nginx cluster advanced settings server-snippet doc

- website/docs/using-qovery/configuration/advanced-settings.md
- website/docs/using-qovery/configuration/advanced-settings.md.erb
> chore(ENG-1927): nginx service advanced settings limit-rps doc

- .github/workflows/gh-pages.yml
> fixing deprecated info in gh-pages.yml

- website/docs/using-qovery/configuration/cluster-advanced-settings.md
- website/docs/using-qovery/configuration/cluster-advanced-settings.md.erb
> feat(QOV-591): add example to dns.coredns.extra_config

- website/docs/getting-started/install-qovery/azure/cluster-managed-by-qovery/create-credentials.md
- website/docs/getting-started/install-qovery/azure/cluster-managed-by-qovery/create-credentials.md.erb
- website/sidebars.js
- website/sidebars.js.erb
- missing credentials in sidebar
- updated text
> fix: update sidebar and text

- website/docs/using-qovery/configuration/cluster-advanced-settings.md.erb
> feat(QOV-1170): EKS support bootlerocket AMI
